# Generated by Django 4.2.8 on 2026-05-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0003_playerprofile_equipped_items'),
        ('game_data', '0004_playeritem_and_link_marketplace'),
    ]

    operations = [
    ]
