# Generated by Django 4.2.8 on 2026-06-02 01:29

from django.db import migrations, models


def migrate_warrior_to_knight(apps, schema_editor):
    PlayerProfile = apps.get_model('game_data', 'PlayerProfile')
    PlayerProfile.objects.filter(class_name='warrior').update(class_name='knight')


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0006_playerprofile_class_name'),
    ]

    operations = [
        migrations.RunPython(migrate_warrior_to_knight),
        migrations.AlterField(
            model_name='playerprofile',
            name='class_name',
            field=models.CharField(choices=[('adventurer', 'Adventurer'), ('mage', 'Mage'), ('archer', 'Archer'), ('knight', 'Knight')], default='adventurer', max_length=16),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='gold',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
