# Generated by Django 4.2.8 on 2026-06-27 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0007_alter_playerprofile_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPendingDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_data', models.JSONField(blank=True, default=dict, null=True)),
                ('gold_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_drops', to='game_data.playerprofile')),
            ],
            options={
                'db_table': 'player_pending_drop',
                'ordering': ['-created_at'],
            },
        ),
    ]
